<header class="mb-auto d-flex justify-content-between">
	<div class="float-md-start d-inline-flex">
		<div class="dropdown">
			<button class="btn btn-link btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
				<i class="fa-solid fa-angles-down"></i>
			</button>
			<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
				<li><a class="dropdown-item" href="https://draw.{{FQDN}}"><img src="img/onnli-draw-mini.png" /> <span class="align-bottom ms-2">Whiteboard</span></a></li>
				<li><a class="dropdown-item" href="https://jam.{{FQDN}}"><img src="img/onnli-jam-mini.png" /> <span class="align-bottom ms-2">Voice Jam</span></a></li>
				<li><a class="dropdown-item" href="https://meet.{{FQDN}}"><img src="img/onnli-meet-mini.png" /> <span class="align-bottom ms-2">Video Room</span></a></li>
				<li><a class="dropdown-item" href="https://mail.{{FQDN}}"><img src="img/onnli-mail-mini.png" /> <span class="align-bottom ms-2">Mail Forwarding</span></a></li>
				<li><a class="dropdown-item" href="https://page.{{FQDN}}"><img src="img/onnli-page-mini.png" /> <span class="align-bottom ms-2">Mini Page</span></a></li>
				<li><a class="dropdown-item" href="https://cal.{{FQDN}}"><img src="img/onnli-cal-mini.png" /> <span class="align-bottom ms-2">Scheduling Tool</span></a></li>
				<li><a class="dropdown-item" href="https://drop.{{FQDN}}"><img src="img/onnli-drop-mini.png" /> <span class="align-bottom ms-2">File Transfer</span></a></a></li>
				<li class="active"><a class="dropdown-item" href="https://share.{{FQDN}}"><img src="img/onnli-share-mini.png" /> <span class="align-bottom ms-2">File Share</span></a></li>
				<li><a class="dropdown-item" href="https://short.{{FQDN}}"><img src="img/onnli-short-mini.png" /> <span class="align-bottom ms-2">URL Shorting</span></a></li>
				<li><a class="dropdown-item" href="https://bin.{{FQDN}}"><img src="img/onnli-bin-mini.png" /> <span class="align-bottom ms-2">Paste Tool</span></a></li>
				<li><a class="dropdown-item" href="https://snip.{{FQDN}}"><img src="img/onnli-snip-mini.png" /> <span class="align-bottom ms-2">Code Snipped</span></a></li>
				<li><a class="dropdown-item" href="https://tools.{{FQDN}}"><img src="img/onnli-tools-mini.png" /> <span class="align-bottom ms-2">Others Tools</span></a></li>
				<li><a class="dropdown-item" href="https://status.{{FQDN}}"><img src="img/onnli-status-mini.png" /> <span class="align-bottom ms-2">Status</span></a></li>
				<li><a class="dropdown-item" href="https://feedback.{{FQDN}}"><span class="align-bottom">Feedback</span></a></li>
			</ul>
		</div>
		<h3 class="mb-0"><a href="/"><img src="img/onnli-share-mini.png" alt="{{siteName}}" /></a></h3>
	</div>
	<nav class="nav nav-masthead justify-content-center float-md-end">
		<a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#modal-faq">FAQ</a>
		<a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#modal-requests">Requests</a>
		<a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#modal-contact">Contact</a>
	</nav>
</header>
